#! /bin/bash

#
# This script generates the image files used in the ARM Trusted Firmware Reset
# Design document from the 'int_handling.dia' file.
#
# The PNG files in the present directory have been generated using Dia version
# 0.97.2, which can be obtained from https://wiki.gnome.org/Apps/Dia/Download
#

set -e

# Usage: generate_image <layers> <image_filename>
function generate_image
{
	dia				\
		--show-layers=$1	\
		--filter=png		\
		--export=$2		\
		int_handling.dia

}

# The 'int_handling.dia' file is organized in several layers.
# Each image is generated by combining and exporting the appropriate set of
# layers.
generate_image								\
	sec_int_bg,legend,sec_int_note,sec_int_handling\
	sec-int-handling.png

generate_image								\
    non_sec_int_bg,legend,non_sec_int_note,non_sec_int_handling\
	non-sec-int-handling.png
